# Generated by Django 3.2.8 on 2021-10-11 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0003_auto_20211011_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users who are connected to the classroom', to=settings.AUTH_USER_MODEL),
        ),
    ]
