# Generated by Django 3.2.8 on 2021-10-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='classroom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
