# Generated by Django 3.2.8 on 2021-11-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_remove_classroom_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='oneway',
            field=models.BooleanField(default=False),
        ),
    ]
