# Generated by Django 3.2.8 on 2021-11-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_classroom_oneway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='oneway',
            field=models.BooleanField(default=True),
        ),
    ]
