# Generated by Django 3.2.8 on 2022-03-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_alter_classroom_oneway'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='board',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
