# Generated by Django 3.2.8 on 2022-03-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_classroom_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='board',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
